### ISSUE TITLE
Timepicker doesn't show

### ISSUE THREAD

**Issue by lorro** [reduxframework/redux-extensions#212]
Hi,

I just bought your DateTime picker extension and I managed to get it to function in the admin panel. Except the timepicker won't show. The datepicker pops out without problems but the timepicker just stays a text input field when I put the focus to it.

Any idea what I could be doing wrong? 

![2015-07-14_142901](https://cloud.githubusercontent.com/assets/977617/8673181/bcb729f4-2a34-11e5-9691-0facf84bfbbb.png)

**Comment by dovy** [comment]
Update your version of Redux to the one in the repo. We fixed the CSS.  ;)

**Comment by lorro** [comment]
I've updated my version of Redux but the timepicker still doesn't pop up :s

**Comment by kprovance** [comment]
Chances are, it's in your config, as mine works fine.  :)

Please provide a support URL  https://docs.reduxframework.com/core/generating-a-support-hash/

**Comment by lorro** [comment]
http://support.redux.io/?id=q4cAUxLE838ZyMv%2Fbvl0SGUAJRzp96CmQQgFEvvEozJmeYHZFQint9pBW%2FOnURYhPS2D7g1jMlPwef6dgG6lfA%3D%3D

**Comment by kprovance** [comment]
I tried your config and was unable to reproduce the issue, the popup appears.  Please check your console log.  See if anything appears when you attempt to click on the date box.

**Comment by lorro** [comment]
Nope, nothing appears in the console and not getting any js errors as well.

**Comment by lorro** [comment]
Apparently another plugin that also incorporates a jquery datepicker messes everything up. When I deactivated that one the timepicker became visible ...
